### ISSUE TITLE
Ctbot no found

### ISSUE THREAD

**Issue by kapotik** [shurillu/CTBot#107]
Hello, since a few days ago all my esp32 with telegram have stopped working, is there an update to do, I am in version 2.1.8

**Comment by shurillu** [comment]
hello kapotik,
   thank you for using the library.
Following your issue report, I've done some tests with this configuration:

- Arduino version: 1.8.15
- Arduino JSON library version: 6.19.4
- ESP8266 board: NodeMCU 1.0
- ESP32 board: Node32s
- ESP8266 toolchain version: 3.0.2 (latest)
- ESP32 toolchain version: 2.0.5 (latest)
- CTBot liberary version: 2.8.1 and 3.0.0

I've encountered no issues at all (ESP8266 with CTBot 2.8.1 and 3.0.0; ESP32 with CTBot 2.8.1 and 3.0.0).
Could you give me more infos about the errors that you encounter? 
Maybe enabling the full debug mode. To do that, find the CTBotDefines.h, look inside for those lines:

```
// enable debugmode -> print debug data on the Serial; Zero -> debug disabled
//#define CTBOT_DEBUG_MODE                 CTBOT_DEBUG_ALL 
#define CTBOT_DEBUG_MODE                 CTBOT_DEBUG_DISABLED 

```

Uncomment the first define and comment the second one.
Regards,

Stefano
