### ISSUE TITLE
connecting to bot ? bit

### ISSUE THREAD

**Issue by LolIoT** [shurillu/CTBot#110]
First of all thanks for great library ! its really cool and modern to do projects with Telegram...
 I've flashed lightBot example via Arduino IDE 1.8.19 to my NodeMCU 1.0 (ESP-12E Module) , but it won't work ,
 i've checked what's in Serial Monitor - and there are some flow .... 
What Im doing wrong ? how can i Fix it ? 

14:26:41.891 -> Starting TelegramBot...
14:26:54.684 -> 
14:26:54.684 -> testConnection OK
14:26:57.862 -> 
14:26:57.862 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
14:26:57.862 -> 
14:26:57.862 -> Soft WDT reset
14:26:57.862 -> 
14:26:57.862 -> >>>stack>>>
14:26:57.862 -> 
14:26:57.862 -> ctx: cont
14:26:57.862 -> sp: 3ffff280 end: e76264f4 offset: 01a0
14:26:57.903 -> 3ffff420:  00000001 00000000 3ffefd24 4020666a  
14:26:57.903 -> 3ffff430:  00000000 00f53628 00003a98 00489526  
.......... many lines like that 
14:27:03.068 -> 40003ab0:  20c06480 89658200 c0ff7a71 65720020  
14:27:03.068 -> 40003ac0:  c0160c84 25420020 204⸮
14:27:03.068 ->  ets Jan  8 2013,rst cause:4, boot mode:(3,6)
14:27:03.068 -> 
14:27:03.068 -> wdt reset
14:27:03.068 -> load 0x4010f000, len 3424, room 16 
14:27:03.068 -> tail 0
14:27:03.068 -> chksum 0x2e
14:27:03.068 -> load 0x3fff20b8, len 40, room 8 
14:27:03.068 -> tail 0
14:27:03.068 -> chksum 0x2b
14:27:03.068 -> csum 0x2b
14:27:03.068 -> v00062a40
14:27:03.068 -> ~ld

**Comment by rafaelspessotto** [comment]
I was having the same problem, it was the ArduinoJson library..cannot be the 6.20. Must be 6.19 (it's incompatible)

**Comment by shurillu** [comment]
As Rafael said, try to use the ArduinoJson version 6.19.4, the newest version (6.20.0) is incompatible for now.

Cheers,

Stefano

**Comment by LolIoT** [comment]
Thanks a lot - that works well
I've just deleted ArduinoJson library in Arduino\Libraries and installed ArduinoJson-v6.19.4
