### ISSUE TITLE
Message not send at bot telegram why?

### ISSUE THREAD

**Issue by ahmadmuhadi** [shurillu/CTBot#115]
Connection Ok But his error to send information in to bot telegram

3ffffcd0:  99999999 3fff1fd4 0000116d 00000000  
3ffffce0:  00001410 00000282 3ffe85f8 00000000  
3ffffcf0:  3ffffdf0 00000008 3fff0604 40202199  
3ffffd00:  3ffe88ff 00000020 3fff069c 40100a88  
3ffffd10:  00000000 3ffee954 3ffffe30 0000000e  
3ffffd20:  00007fed 000000c4 3ffe85f8 4010073a  

tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v00062b20
~ld
��n�r��n|�l�l`bbrl�nB�nl`�rl�l��Starting TelegramBot...

testConnection OK

**Comment by shurillu** [comment]
Hello ahmadmuhadi,
   with the information provided, is impossible to understand what is the problem.
My suggestion is try the echobot example.
Cheers,

Stefano
