### ISSUE TITLE
Exception soft WDT Reset

### ISSUE THREAD

**Issue by CFZxa** [shurillu/CTBot#116]
Call getNewMessage() function will show soft wdt reset.!

**Comment by shurillu** [comment]
Hello CFZxa,

   thank you for your feedback.
Can you be a bit more detailed?
For example:

- SOC (ESP8266/ESP32)
- Arduino ESP8266/ESP32 toolchain/library version
- Arduino IDE/CLI version

Have you tried the EchoBot example?

Regards,

Stefano

**Comment by Abbascloud** [comment]
u can try to use 5.13.5 version of Arduinojson, it resolve this problem for me

**Comment by yodyamahesa** [comment]
> u can try to use 5.13.5 version of Arduinojson, it resolve this problem for me

Switching to Arduinojson version 5.13.5 did the trick for me too. Really appreciate your help! 🙇‍♂️
