### ISSUE TITLE
ArduinoJson 7

### ISSUE THREAD

**Issue by drovosekov** [shurillu/CTBot#124]
Hi.

Is there an update planned for compatibility with ArduinoJson 7

**Comment by shurillu** [comment]
Hello,
   Actually I’ve not planned an update. Are you planning to use the library inside a project that require ArduinoJson v7?

Stefano

**Comment by drovosekov** [comment]
> Hello, Actually I’ve not planned an update. Are you planning to use the library inside a project that require ArduinoJson v7?

Sorry for long time answer.
Yes, I'm use your's library in my project. I try convert itself. And it's work for me. I'm still checking these fixes now...

**Comment by drovosekov** [comment]
https://github.com/shurillu/CTBot/pull/126

**Comment by drovosekov** [comment]
Created fork for JSON v7 support: https://github.com/shurillu/CTBot/pull/126
