### ISSUE TITLE
Problem with uint32_t and ChannelID/GroupID

### ISSUE THREAD

**Issue by Gatlingod** [shurillu/CTBot#18]
Hi,
When i want to send to a channel oder group i see a problem with the uint32_t.

Because channel and group ids are different:

    testbot.sendMessage(-1001287xxxxxx,"testChannel");
    testbot.sendMessage(-31402xxxx,"testGroup");
    testbot.sendMessage(19111xxxx,"testUser");

**Comment by Gatlingod** [comment]
ok, i will test the branch and will write you in the next days if everything works :)

thx :)

**Comment by Gatlingod** [comment]
ok, there is now a problem with int and the keylength:

This is my channel key:
-100128772xxxx
so because of the max of int32 i only get:
-560341xxx

**Comment by shurillu** [comment]
Hi Gatlingod,
   keylength fixed: now it use the int64 data type. You can try it downloading the `Channel-GroupSupport` branch.

I checked the [Telegram bot documentation](https://core.telegram.org/bots/api) and all other indexes seems to be int32 so this version should be the good one.

Let me know if work fine ;-)

Thanks,

Stefano

**Comment by Gatlingod** [comment]
Works great, i use your new code since 5-6 days and dont have any problems.

thx :)

**Comment by shurillu** [comment]
Very well, merged in the master branch.
