### ISSUE TITLE
plus char not passed throw on sendMessage function

### ISSUE THREAD

**Issue by robertmavri** [shurillu/CTBot#27]
Plus char get interpreted as string concentration rather than valid sign in message.

myBot.sendMessage(SECRET_CHAT_ID,"1 + 1 = 3 !!!");

would result on 

1   1 = 3 !!!

To fix above issue following line has to be added to CBot::toURL function:

message.replace("+", "%2B");  // + Plus sign

Hope that helps...

**Comment by shurillu** [comment]
The issue should be corrected as I said in #23
So please check it and let me know.

Stefano

**Comment by shurillu** [comment]
Duplicated. See #23
