### ISSUE TITLE
Blocking when Internet connection drops

### ISSUE THREAD

**Issue by ElVasquito** [shurillu/CTBot#33]
I don't know if this is because of WiFiClientSecure, or if it happens inside the while (telegramServer.isconnected()) loop: when the Internet connection (not Wifi!) drops, the ESP locks up. If the connection returns within a few seconds, it gets back to normal, but if it takes more than 1 minute to return, it will not get back and stay blocked until the ESP is manually restarted. I tried adding a telegramServer.setTimeout(1000); before the connection is made by the Bot, but nothing changes, it blocks the same. Is it possible to avoid this?

**Comment by ElVasquito** [comment]
Solved. Apparently, it was WiFiClientSecure. I updated to the latest code, and now it always unlocks after less than 15 seconds of lost connection. Anyway, I added a 15 second watchdog to my loop(), just in case something bad happens :)

**Comment by shurillu** [comment]
Hi ElVasquito,
   thanks for the feedback, it could be very useful for the community!
Cheers

Stefano
