### ISSUE TITLE
Json5 > json6

### ISSUE THREAD

**Issue by Wailinsoul** [shurillu/CTBot#35]
I just have re-written my entire sketch to use json6 and wanted to incorperate ctbot into it, only to find out this uses 5 :(
Is there any chance you will update ctbot to json6?

**Comment by shurillu** [comment]
Hello Wailinsoul,
   thanks for using the library. 
Migrating to the ArduinoJson version 6.x is a task that I have in mind, but it need some time to review the library (and keep the retro compatibility) so for now, it is in the "to do list". 

Stefano

**Comment by Eugaral** [comment]
I have the same problem with Json5. I would like to have this library with Json6. I think you have done a great job shurillu, is the only library that work good in the arduino community.

**Comment by shurillu** [comment]
Hello, ArduinoJson version 6 is now supported from library version 2.1.0.
In the master branch there is an update (2.1.1) that mitigate some memory management for ESP8266 platform (+15K of heap memory).

Let me know if I can close this issue.

Stefano

**Comment by Wailinsoul** [comment]
Thanks for the update, will try it out.
You can close the issue.
