### ISSUE TITLE
How to get messages form group where is bot is

### ISSUE THREAD

**Issue by 1UnkMan3** [shurillu/CTBot#41]
I try to teach bot answer on messages from one group 
try this if (msg.sender.id == -Idgroud){
                Serial.println("yes");
Can you please help me?

**Comment by shurillu** [comment]
Hi 1UnkMan3,
   you are using the sender ID, so it always answer to the sender, not the group.
Try to use `msg.group.id` instead: `msg.group.id` store the group ID (if any) or the sender ID (if there is no group).
Let me know if this answer your question.
Cheers,

Stefano

**Comment by 1UnkMan3** [comment]
Hello shurillu 
try this
if (myBot.getNewMessage(msg)) {
      Serial.println(msg.sender.id);
        if (msg.group.id == -xxxxxxxxxxxxx){
                Serial.println("yes");
               }
}
But no respond =(

**Comment by 1UnkMan3** [comment]
also try to this without group id
void loop() {
    // a variable to store telegram message data
    TBMessage msg;
    // if there is an incoming message...
    if (myBot.getNewMessage(msg)) {
          if (msg.text.equalsIgnoreCase("Open")) {              // if the received message is "LIGHT ON"...
              digitalWrite(led, HIGH);
              delay(1000);
              digitalWrite(led, LOW);
              delay(500);
              digitalWrite(led, LOW);
              digitalWrite(led, HIGH);
              delay(100);
              digitalWrite(led, LOW);
              myBot.sendMessage(msg.sender.id, "Door opened");  // notify the sender
              Serial.println();
          }

When write direct to the bot it answer. But when I type in group where bot is included nothing happened =(
My goal make bot answer on text in group
Thank you for help =)
