### ISSUE TITLE
where can i declare for ctbot hostname of device ?

### ISSUE THREAD

**Issue by mh4nx7net** [shurillu/CTBot#43]
like on <wifi.h>
there some chance for declare the hostname of device 
by calling wifi.sethostname("hostname")
after calling the ap name by tying wifi.begin("ap_name")
bwt is there any chance too in ctbot ?
thanks before, just wanted recognize my device seen more organized by renaming of my esp-a89002 hostname sort by the name of where node is placed

**Comment by mh4nx7net** [comment]
done
![grimshoot-slurp-2020-03-07-17-56-49](https://user-images.githubusercontent.com/33443311/76142205-fa147c80-609d-11ea-9293-1e6b6381c041.jpg)

you have to found them on
`~/Arduino/libraries/CTBot/src/<here>`

just adding as a third argue
======[project.ino/cpp]=====vvvvv===
`bot_tele.wifiConnect(ssid, pass, hostname);`

then don't forget on which library you'll use, ex: 'CTBot.h:53'
`bool wifiConnect(String ssid, String password = "", String hostname = "");`

finally on 'CTBot.cpp:544' bottom of WiFi.begin
`WiFi.hostname(hostname.c_str());`

then compile.

**Comment by shurillu** [comment]
Good work, I'll add in the next release.
Cheers,
Stefano
