### ISSUE TITLE
Default api.telegram IP dont work 

### ISSUE THREAD

**Issue by lues1980** [shurillu/CTBot#44]
I am not sure, but guess this info may be useful - this night, default (in library) ip adress of telegram api server (149.154.167.198) don't work and bot don't answer even in examples. First, i change to 149.154.167.220, and later set  `m_useDNS = true;` and both methods work.

May be, telegram change adress?

**Comment by shurillu** [comment]
Hello Lues1980,
   I just checked with `myBot.useDNS(true)` (so the library use the URL "api.telegram.org") and `myBot.useDNS(false)` (so the library use the fixed IP "149.154.167.198"): it work with no issues.

Could you check please? Maybe the Telegram guys fixed the IP issue...

Thanks,

Stefano
