### ISSUE TITLE
Unable to connect to Telegram server getNewMessage error: response with no data

### ISSUE THREAD

**Issue by hamster66** [shurillu/CTBot#47]
Hi again : )
Yesterday, all versions where the address 149.154.167.220 is registered stopped working :(
Debugging displays message:
`Unable to connect to Telegram server  getNewMessage error: response with no data`
How to fix it?

**Comment by hamster66** [comment]
I fix it!
New fingerptint in api.telegram.org:
`const uint8_t fingerprint[20] = {0xF2,0xAD,0x29,0x9C,0x34,0x48,0xDD,0x8D,0xF4,0xCF,0x52,0x32,0xF6,0x57,0x33,0x68,0x2E,0x81,0xC1,0x90 };`

**Comment by shurillu** [comment]
Hello Hamster66, 
  the Telegram https certificate was renewed and a new fingerprint must be updated. Using the new one (as you point out!) will make the library works again.

Good job man ;-)

Stefano
