### ISSUE TITLE
my.Bot testConnection always not ok

### ISSUE THREAD

**Issue by magngnu** [shurillu/CTBot#54]
anyone can help me, how to solve if my nodemcu 8266 can't connect with bot telegram and its connected with my Access point? please help

**Comment by mad-b** [comment]
Could this be the issue #52 ? My Bot also stopped responding since a couple of days now...

**Comment by magngnu** [comment]
yes i've normally router but it still same serial monitor always show connection not ok

**Comment by IgorBurkovAlmaty** [comment]
https://github.com/shurillu/CTBot/pull/53/commits/0576f89188d62148d90564e7b247d532950e4db8

**Comment by magngnu** [comment]
im sorry igor, i dont understand what should i do

**Comment by Di-Strix** [comment]
@magngnu you need to download library from [this fork](https://github.com/Di-Strix/CTBot) and replace it

**Comment by IgorBurkovAlmaty** [comment]
\Documents\Arduino\libraries\CTBot\src
You need to make changes to the library files: CTBot.cpp  and CTBot.h

**Comment by magngnu** [comment]
should i remove the last library?

**Comment by magngnu** [comment]
thank u its work, maybe next i still need help

**Comment by salvatore-1981** [comment]
> \ Documents \ Arduino \ libraries \ CTBot \ src
> È necessario apportare modifiche ai file della libreria: CTBot.cpp e CTBot.h 
Ciao, cosa dovrei cambiare

**Comment by Di-Strix** [comment]
@salvatore-1981 you can just download [modified library](https://github.com/Di-Strix/CTBot) and replace it

**Comment by salvatore-1981** [comment]
> @ salvatore-1981 puoi semplicemente scaricare la [libreria modificata](https://github.com/Di-Strix/CTBot) e installarla invece originale

Grazie, provo a scaricare la ctbot 1.4.1e provo

**Comment by magngnu** [comment]
thanks all, anyone can help me for this issues https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/issues/178

**Comment by Di-Strix** [comment]
That's the same way to fix it. Why not using this library? And universal bot has last update from author over two years ago. Does it matter to use it?

**Comment by magngnu** [comment]
because i dont understand how to change from universal bot to ctbot. can u help me ? this my code:  

[project1.txt](https://github.com/shurillu/CTBot/files/4745736/project1.txt)

**Comment by Di-Strix** [comment]
Sorry, I can't, because it need time to learn your sketch and make changes to it. I can help you, but not do instead of you. 
These libraries work by a pretty same way. Please, see examples to understand more.

**Comment by magngnu** [comment]
Okay, no problem. maybe anyone can solve for this https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/issues/178

**Comment by shurillu** [comment]
Hello to all,
   this issue is related to #52 so, as the library now works without patches (probably it was a Telegram related issue), I'll close it.

Stefano
