### ISSUE TITLE
Actively push notification to Telegram user

### ISSUE THREAD

**Issue by nkebx2** [shurillu/CTBot#57]
Good day, thanks for sharing this library. 

I tried to measure the temperature of my server room with some temperature sensors and I wanted the bot to actively inform me if the server room exceeded certain temperature. 

I wonder this could be done in this library, thanks!

**Comment by shurillu** [comment]
Hello nkebx2,
   sure, it 's possible!
You have to do:
- read the temperature data and check if it exceed the threshold
- if yes, send a message to a defined Telegram ID (yours, for example). The text message could contains even the temperature value (for example)

There are a lot of online services for discovering your own Telegram ID but you can modify the echobot example to reply with the sender Telegram ID.
Cheers, 

Stefano

**Comment by nkebx2** [comment]
Hello shurillu,

It work like charm, thanks for your reply, please keep up the good work!
