### ISSUE TITLE
Unable to connect to Telegram server  

### ISSUE THREAD

**Issue by hamster66** [shurillu/CTBot#67]
Hi Stefano!
I decided to transfer my project to the fresh version CTBot  (v 3.0.0 ) and ArduinoJson (v 6. 16.1) on ESP8266 
Compiling test echoBot with CTBOT_DEBUG_ALL
I receive
`
Starting TelegramBot...
--->connect: Connecting to XXXX......
--->connect: WiFi connected
--->connect: IP address: 192.168.1.243
--->connect: Unable to connect to Telegram server
--->sendCommand: Header
POST /botxxx...xxx/getMe HTTP/1.1
Host: api.telegram.org
Content-Length: 5
Content-Type: application/json

--->sendCommand: Payload
null

testConnection NOK
--->connect: Unable to connect to Telegram server
--->sendCommand: Header
POST /botxxx...xxx/getUpdates HTTP/1.1
Host: api.telegram.org
Content-Length: 66
Content-Type: application/json

--->sendCommand: Payload
{"limit":1,"allowed_updates":"message,callback_query","offset":0}
--->connect: Unable to connect to Telegram server
--->sendCommand: Header
...

`
What am I missing? What to look for?
Thanks in advance :)

**Comment by hamster66** [comment]
I'm a donkey!
All SSL siphers has been disabled
Everything worked :)

**Comment by shurillu** [comment]
Hi Hamster66,

   good news! So can we close this issue?

Cheers,

Stefano

**Comment by hamster66** [comment]
Yes. Please close it
