### ISSUE TITLE
Limited possibility

### ISSUE THREAD

**Issue by 20flint12** [shurillu/CTBot#74]
Network connection settings are set only by hardcode. How to use the bot with AutoConnect library?

**Comment by shurillu** [comment]
Hello 20flint12,

   thank you for using the library. 
All the connection member functions provided by the library are helper functions: in other words you can use it or you can use other functions/libraries to set up a connection to a WiFi network.
The only required member function is `setTelegramToken()`. 

Regards,

Stefano

**Comment by 20flint12** [comment]
Thanks. Helped.
