### ISSUE TITLE
Getting Exception (29)

### ISSUE THREAD

**Issue by mwda** [shurillu/CTBot#8]
Can you help me please. I am trying to put the Bot for sending messages along with a sketch that sends and receives InfraRed signals along with the collected temperature. when the bot is going to get started I get the exception (29).
Follows my error with debug.

10:10:39.328 -> ESP8266 IR Controller
10:10:39.328 -> Config pin GPIO5 set to: 1
10:10:39.328 -> wifi evt: 2
mounted file system
10:10:39.363 -> reading config file
10:10:39.363 -> opened config file
10:10:39.363 -> {"hostname":"irblaster","passcode":"","port_str":"80","user_id":"","botToken":"","ip":"192.168.1.11","gw":"192.168.1.1","sn":"255.255.255.0"}
10:10:39.363 -> parsed json
10:10:39.363 -> *WM: Adding parameter
10:10:39.363 -> *WM: hostname
10:10:39.363 -> *WM: Adding parameter
10:10:39.363 -> *WM: passcode
10:10:39.363 -> *WM: Adding parameter
10:10:39.363 -> *WM: port_str
10:10:39.363 -> *WM: Adding parameter
10:10:39.398 -> *WM: user_id
10:10:39.398 -> *WM: Adding parameter
10:10:39.398 -> *WM: botToken
10:10:39.398 -> Using Static IP
10:10:39.398 -> *WM: 
10:10:39.398 -> *WM: AutoConnect
10:10:39.398 -> *WM: Connecting as wifi client...
10:10:39.398 -> *WM: Custom STA IP/GW/Subnet
10:10:39.398 -> *WM: 192.168.1.11
10:10:39.398 -> *WM: Using last saved values, should be faster
wifi evt: 0
10:10:41.582 -> wifi evt: 3
10:10:41.582 -> *WM: Connection result: 
10:10:41.582 -> *WM: 3
10:10:41.582 -> *WM: IP Address:
10:10:41.582 -> *WM: 192.168.1.11
10:10:41.616 -> WiFi connected! User chose hostname 'irblaster' passcode '' and port '80'
10:10:41.616 -> *WM: freeing allocated params!
10:10:41.616 -> WiFi configuration complete
10:10:41.616 -> Local IP: 192.168.1.11
10:10:41.616 -> URL to send commands: http://irblaster.local:80
10:10:41.616 -> HTTP Server started on port 80
10:10:41.616 -> [HTTP-Client][begin] host: checkip.dyndns.org port: 8245 uri: /
10:10:41.616 -> [hostByName] request IP for: checkip.dyndns.org
[hostByName] Host: checkip.dyndns.org IP: 216.146.43.70
[HTTP-Client] connected to checkip.dyndns.org:8245
10:10:42.067 -> [HTTP-Client] sending request header
10:10:42.067 -> -----
10:10:42.067 -> GET / HTTP/1.1
10:10:42.102 -> Host: checkip.dyndns.org:8245
10:10:42.102 -> User-Agent: ESP8266HTTPClient
10:10:42.102 -> Connection: close
10:10:42.102 -> Accept-Encoding: identity;q=1,chunked;q=0.1,*;q=0
10:10:42.102 -> 
10:10:42.102 -> -----
[HTTP-Client][handleHeaderResponse] RX: 'HTTP/1.1 200 OK'
10:10:42.379 -> [HTTP-Client][handleHeaderResponse] RX: 'Content-Type: text/html'
10:10:42.379 -> [HTTP-Client][handleHeaderResponse] RX: 'Server: DynDNS-CheckIP/1.0.1'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: 'Connection: close'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: 'Cache-Control: no-cache'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: 'Pragma: no-cache'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: 'Content-Length: 102'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: ''
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] code: 200
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] size: 102
10:10:42.449 -> [HTTP-Client][writeToStreamDataBlock] connection closed or file end (written: 102).
10:10:42.449 -> [HTTP-Client][end] tcp is closed
10:10:42.449 -> External IP: 177.1.74.5
10:10:42.449 -> [HTTP-Client][end] tcp is closed
10:10:42.449 -> External IP address request took 828 ms
10:10:42.449 -> Ready to send and receive IR signals
10:10:42.449 -> Iniciando TelegramBot...
10:10:42.449 -> Passou

10:10:43.045 -> Exception (29):
10:10:43.045 -> epc1=0x4022a1f8 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
10:10:43.045 -> 
10:10:43.045 -> ctx: cont 
10:10:43.045 -> sp: 3fff57b0 end: 3fff6100 offset: 01a0
10:10:43.045 -> 
10:10:43.045 -> >>>stack>>>
10:10:43.045 -> 3fff5950:  00000000 00000000 00000100 40235ae1  
10:10:43.045 -> 3fff5960:  00000037 00000083 3fff631c 00000000  
10:10:43.045 -> 3fff5970:  00000030 3fff954f 3fff5dac 40235f62  
3fff5980:  00000000 00000000 3ffee9d2 40235e09  
10:10:43.073 -> 3fff5990:  3fffb684 0000002a 00000003 40235caa  
10:10:43.073 -> 3fff59a0:  00000000 3fffb684 3fff954f 00000000  
10:10:43.073 -> 3fff59b0:  00000004 3fffb684 3fff954f 4022df22  
10:10:43.073 -> 3fff59c0:  000005c0 00000000 5b95f516 5e1fe3bd  
10:10:43.100 -> 3fff59d0:  28f76396 58075878 52772c70 d84917b2  
10:10:43.100 -> 3fff59e0:  12cda52f 7dc12838 d5da46fe 21024356  
10:10:43.100 -> 3fff59f0:  2900fb00 7e2329bc f518e286 8b03112b  
10:10:43.100 -> 3fff5a00:  1dafe04d ea078799 ab306bd5 f6e7ec7c  
10:10:43.134 -> 3fff5a10:  00008011 00000000 00000000 00000000  
10:10:43.134 -> 3fff5a20:  00000000 482d0000 feefeffe feefeffe  
10:10:43.134 -> 3fff5a30:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.134 -> 3fff5a40:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.134 -> 3fff5a50:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.134 -> 3fff5a60:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.169 -> 3fff5a70:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.169 -> 3fff5a80:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.169 -> 3fff5a90:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.169 -> 3fff5aa0:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.169 -> 3fff5ab0:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.203 -> 3fff5ac0:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.203 -> 3fff5ad0:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.203 -> 3fff5ae0:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.203 -> 3fff5af0:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.203 -> 3fff5b00:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.238 -> 3fff5b10:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.238 -> 3fff5b20:  feefeffe feefeffe feefeffe feefeffe  
10:10:43.238 -> 3fff5b30:  feefeffe 3fff5c23 feefeffe feefeffe  
10:10:43.238 -> 3fff5b40:  feefeffe feefeffe feefeffe 40228c00  
10:10:43.238 -> 3fff5b50:  3fff5c80 3ffe8304 3fff5be0 40224351  
10:10:43.273 -> 3fff5b60:  00000002 00000000 0000000a 00000000  
10:10:43.273 -> 3fff5b70:  00000002 00000000 0000000a 00000000  
10:10:43.273 -> 3fff5b80:  40228c00 3fff5c80 3fff5c1f 4022470c  
10:10:43.273 -> 3fff5b90:  00000000 a0000000 00000000 0000001c  
10:10:43.273 -> 3fff5ba0:  00002000 00000002 00002000 0000a000  
10:10:43.307 -> 3fff5bb0:  3fff5c23 00000000 00002000 feefeffe  
10:10:43.307 -> 3fff5bc0:  0000a000 3fff28b0 feefeffe 3ffeea92  
10:10:43.307 -> 3fff5bd0:  00000000 3ffe8304 40001e65 3fff5c24  
10:10:43.307 -> 3fff5be0:  3fff5ca0 00000002 ffffffff 40001e4b  
10:10:43.307 -> 3fff5bf0:  3fff5c23 00000000 00000000 00000000  
10:10:43.342 -> 3fff5c00:  00000000 3ffef6a0 00002200 4000050c  
10:10:43.342 -> 3fff5c10:  3fffc278 401022a4 3fffc200 32000022  
10:10:43.342 -> 3fff5c20:  32303438 00000031 00000020 401011de  
10:10:43.342 -> 3fff5c30:  3ffeee25 401045db 00000000 ffffffff  
10:10:43.342 -> 3fff5c40:  3fff5d10 3fff5d00 0000002c 00000004  
10:10:43.342 -> 3fff5c50:  3ffeea93 00000001 3fff3288 401020ca  
10:10:43.376 -> 3fff5c60:  3ffef6b8 00000000 00000000 4026848c  
10:10:43.376 -> 3fff5c70:  3fffd83c 40002394 0000000f 00000000  
10:10:43.376 -> 3fff5c80:  40001da0 00000064 00000000 0000000a  
10:10:43.376 -> 3fff5c90:  40001f46 00000006 020c8299 3cac14e2  
10:10:43.376 -> 3fff5ca0:  38343032 c9020000 85e99c69 f4bfb9fe  
10:10:43.411 -> 3fff5cb0:  0fe9afea 3580b507 3d6e0073 018b761c  
10:10:43.411 -> 3fff5cc0:  e43d8174 2fcca72c a844dc66 d0ea3f27  
10:10:43.411 -> 3fff5cd0:  cbf1a8a7 3807daea 010302bd 00800100  
10:10:43.411 -> 3fff5ce0:  00000000 3fff5d50 3fff5d50 3fff5d77  
10:10:43.411 -> 3fff5cf0:  40002514 3fffdd3c 0000000c 40268488  
10:10:43.446 -> 3fff5d00:  4026848c 00000004 00000004 00000000  
10:10:43.446 -> 3fff5d10:  00000000 00000000 00000000 3fff5ca0  
10:10:43.446 -> 3fff5d20:  00000000 00000000 3fff631c 402268c4  
10:10:43.446 -> 3fff5d30:  3fff5d50 3fff5d50 00000004 4022ef39  
10:10:43.446 -> 3fff5d40:  3fffb094 00000007 3ffe8304 40226878  
10:10:43.480 -> 3fff5d50:  3fff5d70 3fff5d78 4026837c 00000000  
10:10:43.480 -> 3fff5d60:  4026837c 00000090 702c7752 4022ede2  
10:10:43.480 -> 3fff5d70:  32414853 000a3635 0909093a 25090900  
10:10:43.480 -> 3fff5d80:  20000a64 29554f28 3d00093a 74000a3d  
10:10:43.480 -> 3fff5d90:  6e656c68 0a64253a 00000200 0000027a  
10:10:43.515 -> 3fff5da0:  0000040d 00000002 000004d4 0000019d  
10:10:43.515 -> 3fff5db0:  000003c0 00000001 40220c24 3fff50e0  
10:10:43.515 -> 3fff5dc0:  0000017c 3fff8cd0 00002710 40220ca4  
10:10:43.515 -> 3fff5dd0:  00000000 00000000 3fff631c 40220ce4  
10:10:43.515 -> 3fff5de0:  00000000 3fff8ce4 000006ce 00000001  
10:10:43.515 -> 3fff5df0:  3fff8cd0 3fff8e81 000006ce 4022bb95  
10:10:43.549 -> 3fff5e00:  00001426 3fff8d94 0000142d 3fff8ccc  
10:10:43.549 -> 3fff5e10:  3fff8cec 00000007 00ae0011 3fff8de8  
10:10:43.549 -> 3fff5e20:  000004d4 452031ef 64dac81e f199a554  
10:10:43.549 -> 3fff5e30:  69d65ac5 3fffaa14 9f10b232 0000142d  
10:10:43.549 -> 3fff5e40:  3fff8e81 0000142d 3fff8d94 4022d1d2  
10:10:43.582 -> 3fff5e50:  e1477e84 2810a051 e10e3fc8 e9859bce  
10:10:43.582 -> 3fff5e60:  cb46df9f 00000011 0000037d 00000001  
10:10:43.582 -> 3fff5e70:  0000004e 3fffa274 3fffa274 3fffaa14  
10:10:43.582 -> 3fff5e80:  00000000 000013ba 00000064 40220ca4  
10:10:43.582 -> 3fff5e90:  74726543 63696669 20657461 0000142d  
10:10:43.617 -> 3fff5ea0:  3fff8e81 0000142d 3fff8d94 0000142d  
10:10:43.617 -> 3fff5eb0:  3fff8e81 0000142d 3fff8d94 4022cc1c  
10:10:43.617 -> 3fff5ec0:  43728b79 3fff8ba8 00000000 0000000e  
10:10:43.617 -> 3fff5ed0:  00000043 3fff8e81 3fff8d94 4022cff8  
10:10:43.617 -> 3fff5ee0:  00000029 3fff8eb4 00000200 401007ac  
10:10:43.650 -> 3fff5ef0:  3fff5f40 0000000b 00000010 00000000  
10:10:43.650 -> 3fff5f00:  00000000 3fff8d54 3fff8d94 01000000  
10:10:43.650 -> 3fff5f10:  3fff5f40 3fff8d24 3fff8d94 4022cd84  
10:10:43.650 -> 3fff5f20:  00000000 3fff8d24 3fff7be4 3fff7be4  
10:10:43.650 -> 3fff5f30:  00000d89 3fff8d24 3fff5fa0 402170d9  
10:10:43.685 -> 3fff5f40:  3fff5fa0 00000000 3fff8c64 402163fe  
10:10:43.685 -> 3fff5f50:  3fff8c64 00003a98 00000004 00000000  
10:10:43.685 -> 3fff5f60:  00000000 00000000 00000000 3fff8524  
10:10:43.685 -> 3fff5f70:  3fff4ce8 3ffec340 3fff5fa0 4021721c  
10:10:43.685 -> 3fff5f80:  3ffed7b8 c6a79a95 00000000 4010097c  
10:10:43.719 -> 3fff5f90:  3fff60b0 3fff4c18 3fff6010 4021cd57  
10:10:43.719 -> 3fff5fa0:  3ffec100 00000000 00003a98 3fff8524  
10:10:43.719 -> 3fff5fb0:  3fff8548 3fff8c64 3fff8d24 3ffed7b8  
10:10:43.719 -> 3fff5fc0:  c6a79a95 00000000 3ffed7b8 c6a79a95  
10:10:43.719 -> 3fff5fd0:  00000010 0000001c 3fff6020 4021ff69  
10:10:43.753 -> 3fff5fe0:  3fff602c 3fff6020 3fff6020 4021ffb6  
10:10:43.753 -> 3fff5ff0:  3ffec340 00000000 00000000 3fff8524  
10:10:43.753 -> 3fff6000:  3fff4ce8 3fff6060 3ffec340 4021cf4c  
10:10:43.753 -> 3fff6010:  3ffec340 00000000 3fff608c 4021ff37  
10:10:43.753 -> 3fff6020:  3fff8b84 0000000f 00000000 3fff8b64  
10:10:43.787 -> 3fff6030:  0000000f 00000005 3fff8b44 0000000f  
10:10:43.787 -> 3fff6040:  00000000 00000001 3ffede41 40222890  
10:10:43.787 -> 3fff6050:  00000000 3fff4ce8 3ffec340 4021d073  
10:10:43.787 -> 3fff6060:  00000000 00000006 3fff7324 0000000f  
10:10:43.787 -> 3fff6070:  00000000 3fff8aa4 0000000f 00000000  
3fff6080:  3fff8ac4 0000000f 00000000 3fff8b24  
10:10:43.822 -> 3fff6090:  0000000f 00000000 3fff5010 4021fa88  
10:10:43.822 -> 3fff60a0:  00000000 3fff4ce8 3fff5010 4020b514  
10:10:43.822 -> 3fff60b0:  00000000 00000000 00000000 4020cd98  
10:10:43.822 -> 3fff60c0:  00000000 00000000 00000000 feefeffe  
10:10:43.822 -> 3fff60d0:  feefeffe feefeffe feefeffe 3fff50d0  
10:10:43.856 -> 3fff60e0:  3fffdad0 00000000 3fff50c9 40220c67  
10:10:43.856 -> 3fff60f0:  feefeffe feefeffe 3fff50e0 40100a28  
10:10:43.856 -> <<<stack<<<

10:10:43.891 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,0)
10:10:43.891 -> 
10:10:43.891 -> load 0x4010f000, len 1384, room 16 
10:10:43.891 -> tail 8
10:10:43.891 -> chksum 0x2d
10:10:43.891 -> csum 0x2d
10:10:43.891 -> v4ceabea9
10:10:43.891 -> ~ld

**Comment by shurillu** [comment]
Hello,

 

   can you tell me the version of the libraries that are you using?

Could be useful to know:

-          Arduino IDE Version

-          CTBot library version (the last version is 1.2.0)

-          ArduinoJson library version (should be 5.13.2)

-          The board – I guess a NodeMCU ver 1.0

 

Try to update the libraries – pay attention at the version of ArduinoJson: 6.x version does NOT work with CTBot.

Have you tried to run the example provided? For example the echobot example...

 

Let me know, regards

 

Stefano

 

 

Da: mwda [mailto:notifications@github.com] 
Inviato: giovedì 20 settembre 2018 15:19
A: shurillu/CTBot <CTBot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [shurillu/CTBot] Getting Exception (29) (#8)

 

Can you help me please. I am trying to put the Bot for sending messages along with a sketch that sends and receives InfraRed signals along with the collected temperature. when the bot is going to get started I get the exception (29).
Follows my error with debug.

10:10:39.328 -> ESP8266 IR Controller
10:10:39.328 -> Config pin GPIO5 set to: 1
10:10:39.328 -> wifi evt: 2
mounted file system
10:10:39.363 -> reading config file
10:10:39.363 -> opened config file
10:10:39.363 -> {"hostname":"irblaster","passcode":"","port_str":"80","user_id":"","botToken":"","ip":"192.168.1.11","gw":"192.168.1.1","sn":"255.255.255.0"}
10:10:39.363 -> parsed json
10:10:39.363 -> *WM: Adding parameter
10:10:39.363 -> *WM: hostname
10:10:39.363 -> *WM: Adding parameter
10:10:39.363 -> *WM: passcode
10:10:39.363 -> *WM: Adding parameter
10:10:39.363 -> *WM: port_str
10:10:39.363 -> *WM: Adding parameter
10:10:39.398 -> *WM: user_id
10:10:39.398 -> *WM: Adding parameter
10:10:39.398 -> *WM: botToken
10:10:39.398 -> Using Static IP
10:10:39.398 -> *WM:
10:10:39.398 -> *WM: AutoConnect
10:10:39.398 -> *WM: Connecting as wifi client...
10:10:39.398 -> *WM: Custom STA IP/GW/Subnet
10:10:39.398 -> *WM: 192.168.1.11
10:10:39.398 -> *WM: Using last saved values, should be faster
wifi evt: 0
10:10:41.582 -> wifi evt: 3
10:10:41.582 -> *WM: Connection result:
10:10:41.582 -> *WM: 3
10:10:41.582 -> *WM: IP Address:
10:10:41.582 -> *WM: 192.168.1.11
10:10:41.616 -> WiFi connected! User chose hostname 'irblaster' passcode '' and port '80'
10:10:41.616 -> WM: freeing allocated params!
10:10:41.616 -> WiFi configuration complete
10:10:41.616 -> Local IP: 192.168.1.11
10:10:41.616 -> URL to send commands: http://irblaster.local:80
10:10:41.616 -> HTTP Server started on port 80
10:10:41.616 -> [HTTP-Client][begin] host: checkip.dyndns.org port: 8245 uri: /
10:10:41.616 -> [hostByName] request IP for: checkip.dyndns.org
[hostByName] Host: checkip.dyndns.org IP: 216.146.43.70
[HTTP-Client] connected to checkip.dyndns.org:8245
10:10:42.067 -> [HTTP-Client] sending request header
10:10:42.067 -> -----
10:10:42.067 -> GET / HTTP/1.1
10:10:42.102 -> Host: checkip.dyndns.org:8245
10:10:42.102 -> User-Agent: ESP8266HTTPClient
10:10:42.102 -> Connection: close
10:10:42.102 -> Accept-Encoding: identity;q=1,chunked;q=0.1,;q=0
10:10:42.102 ->
10:10:42.102 -> -----
[HTTP-Client][handleHeaderResponse] RX: 'HTTP/1.1 200 OK'
10:10:42.379 -> [HTTP-Client][handleHeaderResponse] RX: 'Content-Type: text/html'
10:10:42.379 -> [HTTP-Client][handleHeaderResponse] RX: 'Server: DynDNS-CheckIP/1.0.1'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: 'Connection: close'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: 'Cache-Control: no-cache'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: 'Pragma: no-cache'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: 'Content-Length: 102'
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] RX: ''
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] code: 200
10:10:42.414 -> [HTTP-Client][handleHeaderResponse] size: 102
10:10:42.449 -> [HTTP-Client][writeToStreamDataBlock] connection closed or file end (written: 102).
10:10:42.449 -> [HTTP-Client][end] tcp is closed
10:10:42.449 -> External IP: 177.1.74.5
10:10:42.449 -> [HTTP-Client][end] tcp is closed
10:10:42.449 -> External IP address request took 828 ms
10:10:42.449 -> Ready to send and receive IR signals
10:10:42.449 -> Iniciando TelegramBot...
10:10:42.449 -> Passou

10:10:43.045 -> Exception (29):
10:10:43.045 -> epc1=0x4022a1f8 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
10:10:43.045 ->
10:10:43.045 -> ctx: cont
10:10:43.045 -> sp: 3fff57b0 end: 3fff6100 offset: 01a0
10:10:43.045 ->
10:10:43.045 -> >>>stack>>>
10:10:43.045 -> 3fff5950: 00000000 00000000 00000100 40235ae1
10:10:43.045 -> 3fff5960: 00000037 00000083 3fff631c 00000000
10:10:43.045 -> 3fff5970: 00000030 3fff954f 3fff5dac 40235f62
3fff5980: 00000000 00000000 3ffee9d2 40235e09
10:10:43.073 -> 3fff5990: 3fffb684 0000002a 00000003 40235caa
10:10:43.073 -> 3fff59a0: 00000000 3fffb684 3fff954f 00000000
10:10:43.073 -> 3fff59b0: 00000004 3fffb684 3fff954f 4022df22
10:10:43.073 -> 3fff59c0: 000005c0 00000000 5b95f516 5e1fe3bd
10:10:43.100 -> 3fff59d0: 28f76396 58075878 52772c70 d84917b2
10:10:43.100 -> 3fff59e0: 12cda52f 7dc12838 d5da46fe 21024356
10:10:43.100 -> 3fff59f0: 2900fb00 7e2329bc f518e286 8b03112b
10:10:43.100 -> 3fff5a00: 1dafe04d ea078799 ab306bd5 f6e7ec7c
10:10:43.134 -> 3fff5a10: 00008011 00000000 00000000 00000000
10:10:43.134 -> 3fff5a20: 00000000 482d0000 feefeffe feefeffe
10:10:43.134 -> 3fff5a30: feefeffe feefeffe feefeffe feefeffe
10:10:43.134 -> 3fff5a40: feefeffe feefeffe feefeffe feefeffe
10:10:43.134 -> 3fff5a50: feefeffe feefeffe feefeffe feefeffe
10:10:43.134 -> 3fff5a60: feefeffe feefeffe feefeffe feefeffe
10:10:43.169 -> 3fff5a70: feefeffe feefeffe feefeffe feefeffe
10:10:43.169 -> 3fff5a80: feefeffe feefeffe feefeffe feefeffe
10:10:43.169 -> 3fff5a90: feefeffe feefeffe feefeffe feefeffe
10:10:43.169 -> 3fff5aa0: feefeffe feefeffe feefeffe feefeffe
10:10:43.169 -> 3fff5ab0: feefeffe feefeffe feefeffe feefeffe
10:10:43.203 -> 3fff5ac0: feefeffe feefeffe feefeffe feefeffe
10:10:43.203 -> 3fff5ad0: feefeffe feefeffe feefeffe feefeffe
10:10:43.203 -> 3fff5ae0: feefeffe feefeffe feefeffe feefeffe
10:10:43.203 -> 3fff5af0: feefeffe feefeffe feefeffe feefeffe
10:10:43.203 -> 3fff5b00: feefeffe feefeffe feefeffe feefeffe
10:10:43.238 -> 3fff5b10: feefeffe feefeffe feefeffe feefeffe
10:10:43.238 -> 3fff5b20: feefeffe feefeffe feefeffe feefeffe
10:10:43.238 -> 3fff5b30: feefeffe 3fff5c23 feefeffe feefeffe
10:10:43.238 -> 3fff5b40: feefeffe feefeffe feefeffe 40228c00
10:10:43.238 -> 3fff5b50: 3fff5c80 3ffe8304 3fff5be0 40224351
10:10:43.273 -> 3fff5b60: 00000002 00000000 0000000a 00000000
10:10:43.273 -> 3fff5b70: 00000002 00000000 0000000a 00000000
10:10:43.273 -> 3fff5b80: 40228c00 3fff5c80 3fff5c1f 4022470c
10:10:43.273 -> 3fff5b90: 00000000 a0000000 00000000 0000001c
10:10:43.273 -> 3fff5ba0: 00002000 00000002 00002000 0000a000
10:10:43.307 -> 3fff5bb0: 3fff5c23 00000000 00002000 feefeffe
10:10:43.307 -> 3fff5bc0: 0000a000 3fff28b0 feefeffe 3ffeea92
10:10:43.307 -> 3fff5bd0: 00000000 3ffe8304 40001e65 3fff5c24
10:10:43.307 -> 3fff5be0: 3fff5ca0 00000002 ffffffff 40001e4b
10:10:43.307 -> 3fff5bf0: 3fff5c23 00000000 00000000 00000000
10:10:43.342 -> 3fff5c00: 00000000 3ffef6a0 00002200 4000050c
10:10:43.342 -> 3fff5c10: 3fffc278 401022a4 3fffc200 32000022
10:10:43.342 -> 3fff5c20: 32303438 00000031 00000020 401011de
10:10:43.342 -> 3fff5c30: 3ffeee25 401045db 00000000 ffffffff
10:10:43.342 -> 3fff5c40: 3fff5d10 3fff5d00 0000002c 00000004
10:10:43.342 -> 3fff5c50: 3ffeea93 00000001 3fff3288 401020ca
10:10:43.376 -> 3fff5c60: 3ffef6b8 00000000 00000000 4026848c
10:10:43.376 -> 3fff5c70: 3fffd83c 40002394 0000000f 00000000
10:10:43.376 -> 3fff5c80: 40001da0 00000064 00000000 0000000a
10:10:43.376 -> 3fff5c90: 40001f46 00000006 020c8299 3cac14e2
10:10:43.376 -> 3fff5ca0: 38343032 c9020000 85e99c69 f4bfb9fe
10:10:43.411 -> 3fff5cb0: 0fe9afea 3580b507 3d6e0073 018b761c
10:10:43.411 -> 3fff5cc0: e43d8174 2fcca72c a844dc66 d0ea3f27
10:10:43.411 -> 3fff5cd0: cbf1a8a7 3807daea 010302bd 00800100
10:10:43.411 -> 3fff5ce0: 00000000 3fff5d50 3fff5d50 3fff5d77
10:10:43.411 -> 3fff5cf0: 40002514 3fffdd3c 0000000c 40268488
10:10:43.446 -> 3fff5d00: 4026848c 00000004 00000004 00000000
10:10:43.446 -> 3fff5d10: 00000000 00000000 00000000 3fff5ca0
10:10:43.446 -> 3fff5d20: 00000000 00000000 3fff631c 402268c4
10:10:43.446 -> 3fff5d30: 3fff5d50 3fff5d50 00000004 4022ef39
10:10:43.446 -> 3fff5d40: 3fffb094 00000007 3ffe8304 40226878
10:10:43.480 -> 3fff5d50: 3fff5d70 3fff5d78 4026837c 00000000
10:10:43.480 -> 3fff5d60: 4026837c 00000090 702c7752 4022ede2
10:10:43.480 -> 3fff5d70: 32414853 000a3635 0909093a 25090900
10:10:43.480 -> 3fff5d80: 20000a64 29554f28 3d00093a 74000a3d
10:10:43.480 -> 3fff5d90: 6e656c68 0a64253a 00000200 0000027a
10:10:43.515 -> 3fff5da0: 0000040d 00000002 000004d4 0000019d
10:10:43.515 -> 3fff5db0: 000003c0 00000001 40220c24 3fff50e0
10:10:43.515 -> 3fff5dc0: 0000017c 3fff8cd0 00002710 40220ca4
10:10:43.515 -> 3fff5dd0: 00000000 00000000 3fff631c 40220ce4
10:10:43.515 -> 3fff5de0: 00000000 3fff8ce4 000006ce 00000001
10:10:43.515 -> 3fff5df0: 3fff8cd0 3fff8e81 000006ce 4022bb95
10:10:43.549 -> 3fff5e00: 00001426 3fff8d94 0000142d 3fff8ccc
10:10:43.549 -> 3fff5e10: 3fff8cec 00000007 00ae0011 3fff8de8
10:10:43.549 -> 3fff5e20: 000004d4 452031ef 64dac81e f199a554
10:10:43.549 -> 3fff5e30: 69d65ac5 3fffaa14 9f10b232 0000142d
10:10:43.549 -> 3fff5e40: 3fff8e81 0000142d 3fff8d94 4022d1d2
10:10:43.582 -> 3fff5e50: e1477e84 2810a051 e10e3fc8 e9859bce
10:10:43.582 -> 3fff5e60: cb46df9f 00000011 0000037d 00000001
10:10:43.582 -> 3fff5e70: 0000004e 3fffa274 3fffa274 3fffaa14
10:10:43.582 -> 3fff5e80: 00000000 000013ba 00000064 40220ca4
10:10:43.582 -> 3fff5e90: 74726543 63696669 20657461 0000142d
10:10:43.617 -> 3fff5ea0: 3fff8e81 0000142d 3fff8d94 0000142d
10:10:43.617 -> 3fff5eb0: 3fff8e81 0000142d 3fff8d94 4022cc1c
10:10:43.617 -> 3fff5ec0: 43728b79 3fff8ba8 00000000 0000000e
10:10:43.617 -> 3fff5ed0: 00000043 3fff8e81 3fff8d94 4022cff8
10:10:43.617 -> 3fff5ee0: 00000029 3fff8eb4 00000200 401007ac
10:10:43.650 -> 3fff5ef0: 3fff5f40 0000000b 00000010 00000000
10:10:43.650 -> 3fff5f00: 00000000 3fff8d54 3fff8d94 01000000
10:10:43.650 -> 3fff5f10: 3fff5f40 3fff8d24 3fff8d94 4022cd84
10:10:43.650 -> 3fff5f20: 00000000 3fff8d24 3fff7be4 3fff7be4
10:10:43.650 -> 3fff5f30: 00000d89 3fff8d24 3fff5fa0 402170d9
10:10:43.685 -> 3fff5f40: 3fff5fa0 00000000 3fff8c64 402163fe
10:10:43.685 -> 3fff5f50: 3fff8c64 00003a98 00000004 00000000
10:10:43.685 -> 3fff5f60: 00000000 00000000 00000000 3fff8524
10:10:43.685 -> 3fff5f70: 3fff4ce8 3ffec340 3fff5fa0 4021721c
10:10:43.685 -> 3fff5f80: 3ffed7b8 c6a79a95 00000000 4010097c
10:10:43.719 -> 3fff5f90: 3fff60b0 3fff4c18 3fff6010 4021cd57
10:10:43.719 -> 3fff5fa0: 3ffec100 00000000 00003a98 3fff8524
10:10:43.719 -> 3fff5fb0: 3fff8548 3fff8c64 3fff8d24 3ffed7b8
10:10:43.719 -> 3fff5fc0: c6a79a95 00000000 3ffed7b8 c6a79a95
10:10:43.719 -> 3fff5fd0: 00000010 0000001c 3fff6020 4021ff69
10:10:43.753 -> 3fff5fe0: 3fff602c 3fff6020 3fff6020 4021ffb6
10:10:43.753 -> 3fff5ff0: 3ffec340 00000000 00000000 3fff8524
10:10:43.753 -> 3fff6000: 3fff4ce8 3fff6060 3ffec340 4021cf4c
10:10:43.753 -> 3fff6010: 3ffec340 00000000 3fff608c 4021ff37
10:10:43.753 -> 3fff6020: 3fff8b84 0000000f 00000000 3fff8b64
10:10:43.787 -> 3fff6030: 0000000f 00000005 3fff8b44 0000000f
10:10:43.787 -> 3fff6040: 00000000 00000001 3ffede41 40222890
10:10:43.787 -> 3fff6050: 00000000 3fff4ce8 3ffec340 4021d073
10:10:43.787 -> 3fff6060: 00000000 00000006 3fff7324 0000000f
10:10:43.787 -> 3fff6070: 00000000 3fff8aa4 0000000f 00000000
3fff6080: 3fff8ac4 0000000f 00000000 3fff8b24
10:10:43.822 -> 3fff6090: 0000000f 00000000 3fff5010 4021fa88
10:10:43.822 -> 3fff60a0: 00000000 3fff4ce8 3fff5010 4020b514
10:10:43.822 -> 3fff60b0: 00000000 00000000 00000000 4020cd98
10:10:43.822 -> 3fff60c0: 00000000 00000000 00000000 feefeffe
10:10:43.822 -> 3fff60d0: feefeffe feefeffe feefeffe 3fff50d0
10:10:43.856 -> 3fff60e0: 3fffdad0 00000000 3fff50c9 40220c67
10:10:43.856 -> 3fff60f0: feefeffe feefeffe 3fff50e0 40100a28
10:10:43.856 -> <<<stack<<<

10:10:43.891 -> ets Jan 8 2013,rst cause:2, boot mode:(3,0)
10:10:43.891 ->
10:10:43.891 -> load 0x4010f000, len 1384, room 16
10:10:43.891 -> tail 8
10:10:43.891 -> chksum 0x2d
10:10:43.891 -> csum 0x2d
10:10:43.891 -> v4ceabea9
10:10:43.891 -> ~ld

**Comment by shurillu** [comment]
Hello mwda,
   I'm closing this issue, if it still persist, please reopen it (with further details).

Stefano
