### ISSUE TITLE
Parse mode in new versions ( HTML, Markdown etc.)

### ISSUE THREAD

**Issue by hamster66** [shurillu/CTBot#94]
The version I worked with in 2020 had the ability to switch text output modes. In modern versions, I do not see CTBotParseModeType and everything related to it.
How to manage output modes in the modern version of the library?

**Comment by shurillu** [comment]
Hi hamster66,
   are you using the v 2.1.9? If the answer is yes, that's the problem ;-)
The parsing mode is only available in the v3.0.0. You can find it in the v3.0.0 branch [here](https://github.com/shurillu/CTBot/tree/v3.0.0). You have to download it and manually add to the Arduino library (overwriting the old one).
Let me know if it solve your question!
Cheers

Stefano

**Comment by hamster66** [comment]
My mistake. Forgot to checkout v3.0.0
Sorry to bother you

**Comment by shurillu** [comment]
No problem ;-)
