### ISSUE TITLE
Application submission

### ISSUE THREAD

**Issue by NobeliY** [shurillu/CTBot#98]
I want to implement the application submission via CT Bot. How to make acceptance of new messages as an application form?

**Comment by shurillu** [comment]
Hello NobeliY
   I'm not clear how a microcontroller like an ESP32 can handle such problem.
Anyway every Telegram user have his own unique ID, so you can use it to identify as a new/already registered user.
After that, you can ask the required information. For example:
```
<Telegram bot> What's your name?
<User> Stefano
...
```
and so on..
Hoping that can answer your question.
Cheers

Stefano

**Comment by NobeliY** [comment]
Thanks for answer my question. I did this: if bot get '/start' command, he send to user his id and url for forms.
